title: Arno Simons
# logo: /assets/img/logo.png
logo: /assets/img/me.jpeg
description: This is the description
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
twitter_username: arno_simons
