title: Arno Simons
about_me: Social Science Researcher
foto: /assets/img/me_color.jpg
description: This is the description
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
twitter: https://twitter.com/arno_simons
