url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Arno Simons" # the name of your site, e.g. ACME Corp.
remote_theme: pages-themes/minimal@v0.2.0
